import { bodyFont, titleFont } from "@/lib/font";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <div className={`${titleFont.className}`}>deneme</div>
      <div className={`${bodyFont.className}`}>deneme</div>
      <div>deneme2</div>
    </>
  );
}
