import Button from "@/components/button";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <Button disabled type={"secondary"}>
        Guney Unay
      </Button>
    </>
  );
}
